version: '3'

services:
  frontend:
    build:
      context: ./front
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./WebAPI
    ports:
      - "8080:8080"
