version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: WebApl
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 380631159244Kolya
    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./WebApl
    container_name: backend_service
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/WebApl
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 380631159244Kolya
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    build:
      context: ./front
    container_name: frontend_service
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data:
